spring:
  application:
    name: springtemplate
    id: com.sphirye.springtemplate
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
app:
  jwt:
    secret-key: ${APP_JWT_SECRET_KEY}