spring:
  application:
    name: springtemplate
    id: com.sphirye.springtemplate
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
app:
  jwt:
    secret-key: ${APP_JWT_SECRET_KEY}